service: cryptonode-api

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  environment:
    DYNAMODB_CURRENCIES_TABLE: cryptocurrencies
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_CURRENCIES_TABLE}"

functions:
  all-currencies:
    handler: all.list
    events:
      - http:
          path: currencies
          method: get
          cors: true
  transfercoin-price:
    handler: currencies/transfercoin.price
    events:
      - schedule: rate(5 minutes)
  transfercoin-masternodes:
    handler: currencies/transfercoin.masternodes
    events:
      - schedule: rate(5 minutes)
  transfercoin-get:
    handler: currencies/transfercoin.get
    events:
      - http:
          path: currency/tx
          method: get
          cors: true
  pivx-price:
    handler: currencies/pivx.price
    events:
      - schedule: rate(5 minutes)
  pivx-masternodes:
    handler: currencies/pivx.masternodes
    events:
      - schedule: rate(5 minutes)
  pivx-get:
    handler: currencies/pivx.get
    events:
      - http:
          path: currency/pivx
          method: get
          cors: true
  dash-price:
    handler: currencies/dash.price
    events:
      - schedule: rate(5 minutes)
  dash-masternodes:
    handler: currencies/dash.masternodes
    events:
      - schedule: rate(10 minutes)
  dash-get:
    handler: currencies/dash.get
    events:
      - http:
          path: currency/dash
          method: get
          cors: true
  crown-price:
    handler: currencies/crown.price
    events:
      - schedule: rate(5 minutes)
  crown-masternodes:
    handler: currencies/crown.masternodes
    events:
      - schedule: rate(5 minutes)
  crown-get:
    handler: currencies/crown.get
    events:
      - http:
          path: currency/crown
          method: get
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: coin
            AttributeType: S
        KeySchema:
          -
            AttributeName: coin
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_CURRENCIES_TABLE}
